version: "3.8"
services:
  portanic:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go_mod:/go/pkg/mod
    environment:
      GO_ENV: development
      ZOOKEEPER_HOST: zookeeper
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=portanic
      - POSTGRES_USER=portanic
      - POSTGRES_PASSWORD=portanic
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portanic"]
      interval: 10s
      timeout: 5s
      retries: 5
  #zookeeper:
  #image: zookeeper
  #ports:
  #- "2181:2181"
#- "8081:8080"

volumes:
  go_mod:
  db_data:
