// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DataSource struct {
	ID   uuid.UUID
	Name pgtype.Text
}

type MappedDatum struct {
	ID        uuid.UUID
	MappingID uuid.UUID
	Data      []byte
	CreatedAt pgtype.Timestamp
}

type Mapping struct {
	ID         uuid.UUID
	Template   uuid.UUID
	DataSource uuid.UUID
}

type Organization struct {
	ID        uuid.UUID
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type OrganizationsUser struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type OrganizationsUsersRole struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	RoleID         uuid.UUID
}

type Role struct {
	ID          uuid.UUID
	Name        pgtype.Text
	Description pgtype.Text
}

type ServiceCatalog struct {
	ID       uuid.UUID
	Template uuid.UUID
}

type ServiceTemplate struct {
	ID        uuid.UUID
	Name      string
	Fields    []byte
	CreatedBy string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Name      pgtype.Text
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	LastLogin pgtype.Timestamp
}
