// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataSource struct {
	ID   pgtype.UUID
	Name pgtype.Text
	Type interface{}
}

type MappedDatum struct {
	ID        pgtype.UUID
	MappingID pgtype.UUID
	Data      []byte
	CreatedAt pgtype.Timestamp
}

type Mapping struct {
	ID         pgtype.UUID
	Template   pgtype.UUID
	DataSource pgtype.UUID
}

type Organization struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type OrganizationsUser struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	PRIMARY        interface{}
}

type OrganizationsUsersRole struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	RoleID         pgtype.UUID
	PRIMARY        interface{}
}

type Role struct {
	ID          pgtype.UUID
	Name        pgtype.Text
	Description pgtype.Text
}

type ServiceCatalog struct {
	ID       pgtype.UUID
	Template pgtype.UUID
}

type ServiceTemplate struct {
	ID        pgtype.UUID
	Name      string
	Fields    []byte
	CreatedBy string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	LastLogin pgtype.Timestamp
}
